version: '3'

services:
    nginx:
        container_name: nginx
        hostname: nginx_kraken
        image: acrius/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/etc:/etc/nginx
            - ./data/log:/var/log/nginx
            - ./data/www:/var/www/html
